tasks:
  - name: Setup Buildozer
    init: |
      sudo apt update
      sudo apt install -y git zip unzip openjdk-17-jdk autoconf libtool pkg-config \
        zlib1g-dev libncurses5-dev libncursesw5-dev libtinfo5 cmake \
        libffi-dev libssl-dev automake
      pip install --upgrade pip
      pip install buildozer cython

    command: |
      echo "✅ Môi trường Buildozer đã sẵn sàng!"
      echo "Bạn có thể chạy: buildozer android debug"
